name: dtfpl
version: 0.1.0
synopsis: Dynamically typed functional programming language
description: A dynamically typed functional programming language that compiles to JavaScript, with a syntax similar to Haskell.
category: Language
author: Bretton Chen
maintainer: Bretton Chen
copyright: (c) 2017-20 Bretton Chen
license: MIT
github: qsctr/dtfpl
extra-source-files:
  - js/**/*.js
  - package.json
  - stack.yaml
  - README.md
  - docs/**/*.md
dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - containers
  - data-or
  - megaparsec
  - mtl
  - parser-combinators
  - polysemy
  - polysemy-plugin
  - singletons
  - text
  - typed-process
ghc-options:
  - -Wall
  - -Werror
  - -Wwarn=unused-top-binds
  - -Wwarn=unused-local-binds
  - -Wwarn=unused-pattern-binds
  - -Wwarn=unused-matches
  - -Wwarn=unused-imports
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -O2
  - -fplugin=Polysemy.Plugin
  - -flate-specialise
  - -fspecialise-aggressively

library:
  source-dirs: src

executable:
  source-dirs: app
  main: Main.hs
  dependencies:
    - dtfpl
  ghc-options: -threaded
