name: metro
version: 0.3.2
synopsis: A functional programming language
description: A strict, non-pure functional programming language that compiles to JavaScript.
category: Language
author: Bretton Chen
maintainer: Bretton Chen
copyright: (c) 2017-21 Bretton Chen
license: MIT
github: qsctr/metro
extra-source-files:
  - package.json
  - stack.yaml
  - README.md
  - docs/**/*.md
data-files:
  - js/**/*.js
  - node_modules/**/*
dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - co-log-core
  - co-log-polysemy
  - containers
  - megaparsec
  - mtl
  - optparse-applicative
  - parser-combinators
  - pathtype
  - polysemy
  - polysemy-plugin
  - singletons
  - text
  - time
  - typed-process
  - uniplate
ghc-options:
  - -Wall
  - -Werror
  - -Wwarn=unused-top-binds
  - -Wwarn=unused-local-binds
  - -Wwarn=unused-pattern-binds
  - -Wwarn=unused-matches
  - -Wwarn=unused-imports
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -O2
  - -fplugin=Polysemy.Plugin
  - -flate-specialise
  - -fspecialise-aggressively

library:
  source-dirs: src
  generated-other-modules: Paths_metro

executable:
  source-dirs: app
  main: Main.hs
  dependencies:
    - metro
  ghc-options: -threaded
